<?php

namespace ContainerIdmBj4U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FSTBoAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FS_TBoA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FS_TBoA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AddController::addAnnonce' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::adminAnnonces' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'App\\Controller\\AdminController::change' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::deleteAnnonce' => ['privates', '.service_locator.fEltKcs', 'get_ServiceLocator_FEltKcsService', true],
            'App\\Controller\\AdminController::modifyAnnonce' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'App\\Controller\\AllAnnoncesController::detail' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'App\\Controller\\AllAnnoncesController::index' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'App\\Controller\\ProfilController::index' => ['privates', '.service_locator.2rSpiUs', 'get_ServiceLocator_2rSpiUsService', true],
            'App\\Controller\\ReactController::index' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'App\\Controller\\RegisterController::infoRegister' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\TestDatabaseController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::userAnnonces' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AddController:addAnnonce' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:adminAnnonces' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'App\\Controller\\AdminController:change' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:deleteAnnonce' => ['privates', '.service_locator.fEltKcs', 'get_ServiceLocator_FEltKcsService', true],
            'App\\Controller\\AdminController:modifyAnnonce' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'App\\Controller\\AllAnnoncesController:detail' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'App\\Controller\\AllAnnoncesController:index' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'App\\Controller\\ProfilController:index' => ['privates', '.service_locator.2rSpiUs', 'get_ServiceLocator_2rSpiUsService', true],
            'App\\Controller\\ReactController:index' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'App\\Controller\\RegisterController:infoRegister' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\TestDatabaseController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:userAnnonces' => ['privates', '.service_locator.5sXqVh1', 'get_ServiceLocator_5sXqVh1Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AddController::addAnnonce' => '?',
            'App\\Controller\\AdminController::adminAnnonces' => '?',
            'App\\Controller\\AdminController::change' => '?',
            'App\\Controller\\AdminController::deleteAnnonce' => '?',
            'App\\Controller\\AdminController::modifyAnnonce' => '?',
            'App\\Controller\\AllAnnoncesController::detail' => '?',
            'App\\Controller\\AllAnnoncesController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\ProfilController::index' => '?',
            'App\\Controller\\ReactController::index' => '?',
            'App\\Controller\\RegisterController::infoRegister' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TestDatabaseController::index' => '?',
            'App\\Controller\\UserController::userAnnonces' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AddController:addAnnonce' => '?',
            'App\\Controller\\AdminController:adminAnnonces' => '?',
            'App\\Controller\\AdminController:change' => '?',
            'App\\Controller\\AdminController:deleteAnnonce' => '?',
            'App\\Controller\\AdminController:modifyAnnonce' => '?',
            'App\\Controller\\AllAnnoncesController:detail' => '?',
            'App\\Controller\\AllAnnoncesController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\ProfilController:index' => '?',
            'App\\Controller\\ReactController:index' => '?',
            'App\\Controller\\RegisterController:infoRegister' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TestDatabaseController:index' => '?',
            'App\\Controller\\UserController:userAnnonces' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
