<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIdmBj4U\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIdmBj4U/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIdmBj4U.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIdmBj4U\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIdmBj4U\App_KernelDevDebugContainer([
    'container.build_hash' => 'IdmBj4U',
    'container.build_id' => 'c3099105',
    'container.build_time' => 1713480308,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIdmBj4U');
