<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_mui_material_Button_Button_js-node_modules_react-router-dom_dist_index_j-a0c25c.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
    ],
],

]];
